### ISSUE TITLE
Перестала работать после обновы 1.0.4

### ISSUE THREAD

**Issue by g470258** [ANS-spb/homeassistant-openweathermap#2]
Logger: homeassistant.config_entries
Source: custom_components/openweathermap/__init__.py:60
Integration: OpenWeatherMapCustom
First occurred: 09:42:59 (1 occurrences)
Last logged: 09:42:59

Error setting up entry openweathermap for openweathermap
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/openweathermap/__init__.py", line 60, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

**Comment by ANS-spb** [comment]
Откатитесь на релиз 1.0.3, я убрал 1.0.4
Видимо, это был задел под следующую версию ХА

**Comment by g470258** [comment]
Самое интересное откат не помог, сейчас полностью грохну и с 0 поставлю. На бете 2022.8 работает отлично

**Comment by g470258** [comment]
с нуля 1.0.3 заработала, закрываю

**Comment by ANS-spb** [comment]
А у меня откат на 1.0.3 заработал, через hacs -> redownload. Странно.
За отзыв в любом случае спасибо, пора учиться делать бета-версии и тестировать на себе перед релизом
